# Generated by Django 3.2.7 on 2022-08-17 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizzeria',
            old_name='webiste',
            new_name='website',
        ),
    ]
